const FORMAL_META_KEY = "kanjiTankenFormal.meta.v2";
const LEGACY_APP_KEY = "kanjiTankenPhase2Prototype20.v1";
const PROFILE_PREFIX = "kanjiTankenFormal.profile.v2.";
const ROLLBACK_KEY = "kanjiTankenFormal.rollback.v2";
const BACKUP_FORMAT = "kanji-tanken-formal-backup";
const DATASET_ID = "kanji-tanken-prototype20";
const AVATARS = ["🌱", "🌳", "⭐", "🔎", "🐾", "🌈", "🍀", "🚀"];
const originalGetItem = Storage.prototype.getItem;
const originalSetItem = Storage.prototype.setItem;
const originalRemoveItem = Storage.prototype.removeItem;
const rawGet = key => originalGetItem.call(localStorage, key);
const rawSet = (key, value) => originalSetItem.call(localStorage, key, value);
const rawRemove = key => originalRemoveItem.call(localStorage, key);
const nowIso = () => new Date().toISOString();
const makeId = prefix => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
const defaultAppStore = () => ({ version: 1, settings: { lowStim: false, reduceMotion: false, ghostGuide: true, missionCount: 3, choiceCount: 3 }, ui: { lastCharId: "u4e00" }, records: {}, sessions: [] });
function createProfile(code = "P001", nickname = "たんけん1", avatar = "🌱") { const at = nowIso(); return { id: makeId("profile"), code, nickname: String(nickname || code).slice(0, 16), avatar: AVATARS.includes(avatar) ? avatar : "🌱", archived: false, createdAt: at, updatedAt: at }; }
function defaultMeta() { const profile = createProfile(); return { version: 2, datasetId: DATASET_ID, activeProfileId: profile.id, profiles: { [profile.id]: profile }, adminAuth: null, lastExportAt: null, lastImportAt: null, createdAt: nowIso(), updatedAt: nowIso() }; }
function normalizeProfile(profile, code) { const base = createProfile(code, code); return { ...base, ...(profile || {}), id: String(profile?.id || base.id), code: /^P\d{3,}$/.test(String(profile?.code || "")) ? String(profile.code) : code, nickname: String(profile?.nickname || profile?.alias || code).slice(0, 16), avatar: AVATARS.includes(profile?.avatar) ? profile.avatar : "🌱", archived: Boolean(profile?.archived) }; }
function normalizeMeta(value) { const fallback = defaultMeta(); if (!value || value.version !== 2 || !value.profiles) return fallback; const profiles = {}; Object.entries(value.profiles).forEach(([id, profile], index) => { const p = normalizeProfile({ ...profile, id }, `P${String(index + 1).padStart(3, "0")}`); profiles[p.id] = p; }); if (!Object.keys(profiles).length) return fallback; let active = profiles[value.activeProfileId] && !profiles[value.activeProfileId].archived ? value.activeProfileId : Object.values(profiles).find(p => !p.archived)?.id; if (!active) { active = Object.keys(profiles)[0]; profiles[active].archived = false; } return { ...fallback, ...value, version: 2, datasetId: DATASET_ID, profiles, activeProfileId: active, adminAuth: value.adminAuth?.hash && value.adminAuth?.salt ? value.adminAuth : null }; }
let suppressAppSave = false;
let meta;
try { meta = normalizeMeta(JSON.parse(rawGet(FORMAL_META_KEY) || "null")); } catch { meta = defaultMeta(); }
const runtimeProfileId = meta.activeProfileId;
const profileDataKey = id => `${PROFILE_PREFIX}${id}`;
const legacy = rawGet(LEGACY_APP_KEY);
if (legacy && !rawGet(profileDataKey(runtimeProfileId))) rawSet(profileDataKey(runtimeProfileId), legacy);
Storage.prototype.getItem = function(key) { if (this === localStorage && key === LEGACY_APP_KEY) return rawGet(profileDataKey(runtimeProfileId)); return originalGetItem.call(this, key); };
Storage.prototype.setItem = function(key, value) { if (this === localStorage && key === LEGACY_APP_KEY) { if (suppressAppSave) return; return rawSet(profileDataKey(runtimeProfileId), value); } return originalSetItem.call(this, key, value); };
Storage.prototype.removeItem = function(key) { if (this === localStorage && key === LEGACY_APP_KEY) return rawRemove(profileDataKey(runtimeProfileId)); return originalRemoveItem.call(this, key); };
function saveMeta() { meta.updatedAt = nowIso(); rawSet(FORMAL_META_KEY, JSON.stringify(meta)); }
function activeProfile() { return meta.profiles[meta.activeProfileId]; }
function parseProfileStore(id) { try { return { ...defaultAppStore(), ...(JSON.parse(rawGet(profileDataKey(id)) || "null") || {}) }; } catch { return defaultAppStore(); } }
function profileStats(id) { const store = parseProfileStore(id); const cards = Object.values(store.records || {}).filter(record => record.card || Object.values(record.games || {}).filter(game => (game.completed || 0) > 0).length >= 3).length; return { sessions: Array.isArray(store.sessions) ? store.sessions.length : 0, cards }; }
function nextCode() { const nums = Object.values(meta.profiles).map(p => Number(String(p.code).replace(/^P/, ""))).filter(Number.isFinite); return `P${String((nums.length ? Math.max(...nums) : 0) + 1).padStart(3, "0")}`; }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>\"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[c])); }
function $(id) { return document.getElementById(id); }
let unlocked = false, lastAdminActivity = 0, pendingAdminAction = null, pinFailures = 0, pinLockUntil = 0, editingId = null, pendingImport = null, toastTimer = null;
function openModal(el) { el?.classList.add("show"); }
function closeModal(el) { el?.classList.remove("show"); }
function toast(message, error = false) { const el = $("formalToast"); if (!el) return; el.textContent = message; el.classList.toggle("error", error); el.classList.add("show"); clearTimeout(toastTimer); toastTimer = setTimeout(() => el.classList.remove("show"), 2800); }
function renderProfileChrome() { const p = activeProfile(); [["formalProfileAvatar", p.avatar], ["formalProfileName", p.nickname], ["formalProfileCode", p.code], ["formalHomeAvatar", p.avatar], ["formalHomeName", p.nickname], ["formalHomeCode", p.code], ["formalAdultCurrent", `${p.code} ${p.nickname}`]].forEach(([id, text]) => { const el = $(id); if (el) el.textContent = text; }); }
function renderSwitchList() { const list = $("formalProfileSwitchList"); if (!list) return; list.innerHTML = ""; Object.values(meta.profiles).filter(p => !p.archived).sort((a,b) => a.code.localeCompare(b.code)).forEach(p => { const stats = profileStats(p.id), button = document.createElement("button"); button.className = `formal-switch-option ${p.id === meta.activeProfileId ? "current" : ""}`; button.innerHTML = `<span>${p.avatar}</span><div><strong>${escapeHtml(p.nickname)}</strong><small>${p.code}・カード${stats.cards}枚</small></div>`; button.addEventListener("click", () => switchProfile(p.id)); list.appendChild(button); }); }
function switchProfile(id) { const p = meta.profiles[id]; if (!p || p.archived) return; meta.activeProfileId = id; saveMeta(); sessionStorage.setItem("formalProfileChosen", "1"); location.reload(); }
function renderAdultProfileSelect() { const select = $("formalAdultProfileSelect"); if (!select) return; select.innerHTML = Object.values(meta.profiles).sort((a,b) => a.code.localeCompare(b.code)).map(p => `<option value="${p.id}">${p.code} ${escapeHtml(p.nickname)}${p.archived ? "（保管中）" : ""}</option>`).join(""); select.value = meta.activeProfileId; }
function makeAction(label, action, danger = false) { const b = document.createElement("button"); b.type = "button"; b.className = `soft-btn${danger ? " danger" : ""}`; b.textContent = label; b.addEventListener("click", action); return b; }
function renderProfileCards() { const box = $("formalProfileCards"); if (!box) return; box.innerHTML = ""; Object.values(meta.profiles).sort((a,b) => a.code.localeCompare(b.code)).forEach(p => { const stats = profileStats(p.id), card = document.createElement("div"); card.className = `formal-profile-card ${p.id === meta.activeProfileId ? "active" : ""} ${p.archived ? "archived" : ""}`; card.innerHTML = `<div class="formal-profile-card-main"><span>${p.avatar}</span><div><strong>${escapeHtml(p.nickname)}</strong><small>${p.code}${p.archived ? "・保管中" : ""}／学習${stats.sessions}回</small></div></div><div class="formal-profile-card-actions"></div>`; const actions = card.querySelector(".formal-profile-card-actions"); const use = makeAction("使う", () => switchProfile(p.id)); use.disabled = p.archived || p.id === meta.activeProfileId; actions.append(use, makeAction("編集", () => openEditor(p.id)), makeAction(p.archived ? "戻す" : "保管", () => p.archived ? restoreProfile(p.id) : archiveProfile(p.id)), makeAction("削除", () => deleteProfile(p.id), true)); box.appendChild(card); }); }
function openEditor(id = null) { editingId = id; const p = id ? meta.profiles[id] : null; $("formalProfileEditorTitle").textContent = p ? `${p.code}を編集` : "匿名プロフィールを追加"; $("formalProfileNameInput").value = p?.nickname || `たんけん${Object.keys(meta.profiles).length + 1}`; $("formalProfileAvatarInput").value = p?.avatar || "🌱"; $("formalProfileEditorError").textContent = ""; openModal($("formalProfileEditor")); }
function saveEditor() { const name = $("formalProfileNameInput").value.trim().slice(0,16), avatar = $("formalProfileAvatarInput").value; if (!name) { $("formalProfileEditorError").textContent = "匿名の呼び名を入力してください。"; return; } if (editingId) { meta.profiles[editingId].nickname = name; meta.profiles[editingId].avatar = avatar; meta.profiles[editingId].updatedAt = nowIso(); } else { const p = createProfile(nextCode(), name, avatar); meta.profiles[p.id] = p; rawSet(profileDataKey(p.id), JSON.stringify(defaultAppStore())); } saveMeta(); closeModal($("formalProfileEditor")); renderFormalUi(); }
function archiveProfile(id) { const active = Object.values(meta.profiles).filter(p => !p.archived); if (active.length <= 1) return toast("利用できるプロフィールを1つ以上残してください。", true); const p = meta.profiles[id]; if (!confirm(`${p.code} ${p.nickname} を保管しますか？\n記録は消えません。`)) return; p.archived = true; if (meta.activeProfileId === id) meta.activeProfileId = active.find(x => x.id !== id).id; saveMeta(); location.reload(); }
function restoreProfile(id) { meta.profiles[id].archived = false; saveMeta(); renderFormalUi(); }
function deleteProfile(id) { const p = meta.profiles[id]; if (!p) return; const available = Object.values(meta.profiles).filter(profile => !profile.archived); if (!p.archived && available.length <= 1) return toast("利用できるプロフィールを1つ以上残してください。", true); if (!confirm(`${p.code} ${p.nickname} の記録を完全に削除しますか？`)) return; delete meta.profiles[id]; rawRemove(profileDataKey(id)); if (meta.activeProfileId === id) { suppressAppSave = true; meta.activeProfileId = Object.values(meta.profiles).find(x => !x.archived)?.id || Object.keys(meta.profiles)[0]; } saveMeta(); location.reload(); }
function bytesToHex(buffer) { return [...new Uint8Array(buffer)].map(b => b.toString(16).padStart(2, "0")).join(""); }
function hexToBytes(hex) { const clean = String(hex).replace(/[^0-9a-f]/gi, ""), bytes = new Uint8Array(Math.floor(clean.length/2)); for (let i=0;i<bytes.length;i++) bytes[i] = parseInt(clean.slice(i*2,i*2+2),16); return bytes; }
async function derivePin(pin, salt, iterations = 100000) { const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(pin), "PBKDF2", false, ["deriveBits"]); return bytesToHex(await crypto.subtle.deriveBits({ name:"PBKDF2", hash:"SHA-256", salt:hexToBytes(salt), iterations }, key, 256)); }
async function setPin(pin) { const bytes = new Uint8Array(16); crypto.getRandomValues(bytes); const salt = bytesToHex(bytes), iterations = 100000; meta.adminAuth = { salt, iterations, hash: await derivePin(pin,salt,iterations), updatedAt: nowIso() }; }
async function verifyPin(pin) { const a = meta.adminAuth; return Boolean(a && await derivePin(pin,a.salt,a.iterations||100000) === a.hash); }
function validPin(pin) { return /^\d{4,8}$/.test(pin); }
function requireAdmin(reason, action) { if (unlocked && Date.now()-lastAdminActivity < 600000) { lastAdminActivity = Date.now(); action(); return; } pendingAdminAction = action; $("formalPinReason").textContent = reason; $("formalPinInput").value = ""; $("formalPinError").textContent = ""; openModal($("formalPinModal")); setTimeout(() => $("formalPinInput").focus(), 50); }
async function submitPin() { if (Date.now() < pinLockUntil) return $("formalPinError").textContent = `あと${Math.ceil((pinLockUntil-Date.now())/1000)}秒待ってください。`; const pin = $("formalPinInput").value.trim(); if (!validPin(pin)) return $("formalPinError").textContent = "4〜8桁の数字を入力してください。"; if (await verifyPin(pin)) { unlocked = true; lastAdminActivity = Date.now(); pinFailures = 0; closeModal($("formalPinModal")); const action = pendingAdminAction; pendingAdminAction = null; action?.(); } else { pinFailures++; if (pinFailures >= 5) { pinFailures = 0; pinLockUntil = Date.now()+60000; $("formalPinError").textContent = "60秒間ロックします。"; } else $("formalPinError").textContent = `PINが一致しません。あと${5-pinFailures}回試せます。`; } }
function lockAdmin() { unlocked = false; lastAdminActivity = 0; document.querySelector('.nav-btn[data-page="home"]')?.click(); toast("おとな画面をロックしました。"); }
async function sha256(text) { return bytesToHex(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text))); }
function safeClone(value) { return JSON.parse(JSON.stringify(value)); }
function profileForBackup(id) { return { meta: safeClone(meta.profiles[id]), data: parseProfileStore(id) }; }
async function makeBackup(scope) { const ids = scope === "all" ? Object.keys(meta.profiles) : [meta.activeProfileId], payload = { profiles: ids.map(profileForBackup) }; return { format: BACKUP_FORMAT, version: 2, datasetId: DATASET_ID, scope, exportedAt: nowIso(), checksum: await sha256(JSON.stringify(payload)), payload }; }
function downloadJson(value, name) { const blob = new Blob([JSON.stringify(value,null,2)],{type:"application/json"}), url = URL.createObjectURL(blob), a = document.createElement("a"); a.href=url; a.download=name; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(url),1000); }
async function exportBackup(scope) { const backup = await makeBackup(scope), stamp = new Date().toISOString().replace(/[:T]/g,"-").slice(0,16); downloadJson(backup, scope === "all" ? `kanji-tanken-all-${stamp}.json` : `kanji-tanken-${activeProfile().code}-${stamp}.json`); meta.lastExportAt = nowIso(); saveMeta(); renderBackupStatus(); toast("バックアップを書き出しました。"); }
async function validateBackup(value) { if (!value || value.format !== BACKUP_FORMAT || value.version !== 2 || !Array.isArray(value.payload?.profiles) || value.payload.profiles.length === 0) throw new Error("このアプリのバックアップ形式ではありません。"); if (value.datasetId !== DATASET_ID) throw new Error("異なる教材データのバックアップです。"); if (value.payload.profiles.some(entry => !entry || !entry.meta || !entry.data || typeof entry.data !== "object")) throw new Error("バックアップ内の利用者記録が不足しています。"); if (value.checksum && await sha256(JSON.stringify(value.payload)) !== value.checksum) throw new Error("ファイルが破損または変更されています。"); return value; }
async function prepareImport(file) { try { pendingImport = await validateBackup(JSON.parse(await file.text())); const count = pendingImport.payload.profiles.length, sessions = pendingImport.payload.profiles.reduce((n,p)=>n+(p.data?.sessions?.length||0),0); $("formalImportPreview").innerHTML = `<strong>${count}プロフィール</strong><br>学習セッション：${sessions}件<br>書き出し：${new Date(pendingImport.exportedAt).toLocaleString("ja-JP")}`; $("formalImportError").textContent=""; $("formalImportReplace").classList.toggle("hidden", pendingImport.scope !== "all"); openModal($("formalImportModal")); } catch (error) { toast(error.message,true); } finally { $("formalImportFile").value=""; } }
function snapshotForRollback() { const data = {}; Object.keys(meta.profiles).forEach(id => data[id] = rawGet(profileDataKey(id))); rawSet(ROLLBACK_KEY, JSON.stringify({ meta, data })); }
function importRecords(mode) { if (!pendingImport) return; if (mode === "replace" && !confirm("全利用者の記録を入れ替えますか？\n現在のPINは変わりません。")) return; snapshotForRollback(); if (mode === "replace") { suppressAppSave = true; Object.keys(meta.profiles).forEach(id => rawRemove(profileDataKey(id))); const auth = meta.adminAuth, profiles = {}; pendingImport.payload.profiles.forEach((entry,index) => { const p = normalizeProfile({ ...entry.meta, id: makeId("profile") }, /^P\d{3,}$/.test(entry.meta?.code||"") ? entry.meta.code : `P${String(index+1).padStart(3,"0")}`); profiles[p.id]=p; rawSet(profileDataKey(p.id), JSON.stringify(entry.data || defaultAppStore())); }); let activeId = Object.values(profiles).find(p=>!p.archived)?.id; if (!activeId) { activeId = Object.keys(profiles)[0]; profiles[activeId].archived = false; } meta = { ...defaultMeta(), profiles, activeProfileId:activeId, adminAuth:auth, lastImportAt:nowIso(), lastExportAt:meta.lastExportAt }; } else { pendingImport.payload.profiles.forEach(entry => { const code = nextCode(); const p=normalizeProfile({ ...entry.meta, id:makeId("profile"), code, archived:false }, code); meta.profiles[p.id]=p; rawSet(profileDataKey(p.id), JSON.stringify(entry.data || defaultAppStore())); }); meta.lastImportAt=nowIso(); } saveMeta(); location.reload(); }
function rollbackImport() { const raw=rawGet(ROLLBACK_KEY); if (!raw) return toast("取り消せる読み込みがありません。",true); if (!confirm("直前の読み込み前の状態へ戻しますか？")) return; const snap=JSON.parse(raw); suppressAppSave = true; Object.keys(meta.profiles).forEach(id=>rawRemove(profileDataKey(id))); meta=normalizeMeta(snap.meta); Object.entries(snap.data||{}).forEach(([id,data])=>{if(data!==null)rawSet(profileDataKey(id),data);}); rawRemove(ROLLBACK_KEY); saveMeta(); location.reload(); }
function renderBackupStatus() { const el=$("formalBackupStatus"); if (!el) return; el.innerHTML=`最終書き出し：${meta.lastExportAt ? new Date(meta.lastExportAt).toLocaleString("ja-JP") : "まだありません"}<br>最終読み込み：${meta.lastImportAt ? new Date(meta.lastImportAt).toLocaleString("ja-JP") : "まだありません"}${rawGet(ROLLBACK_KEY)?"<br><strong>直前の読み込みを取り消せます。</strong>":""}`; $("formalRollback").disabled=!rawGet(ROLLBACK_KEY); }
function renderFormalUi() { renderProfileChrome(); renderSwitchList(); renderAdultProfileSelect(); renderProfileCards(); renderBackupStatus(); }
function captureAdminGate(selector, reason) { document.querySelector(selector)?.addEventListener("click", event => { if (unlocked) { lastAdminActivity=Date.now(); return; } event.preventDefault(); event.stopImmediatePropagation(); const target=event.currentTarget; requireAdmin(reason,()=>target.click()); }, true); }
function setupEvents() {
  $("formalProfileBtn").addEventListener("click",()=>{renderSwitchList();openModal($("formalProfileSwitch"));}); $("formalHomeSwitch").addEventListener("click",()=>{renderSwitchList();openModal($("formalProfileSwitch"));}); $("formalSwitchClose").addEventListener("click",()=>{sessionStorage.setItem("formalProfileChosen","1");closeModal($("formalProfileSwitch"));});
  $("formalManageProfiles").addEventListener("click",()=>{closeModal($("formalProfileSwitch"));requireAdmin("匿名プロフィールを管理します。",()=>document.querySelector('.nav-btn[data-page="adult"]').click());});
  $("formalSetupSubmit").addEventListener("click",async()=>{const pin=$("formalSetupPin").value.trim(),confirmPin=$("formalSetupPinConfirm").value.trim(),name=$("formalSetupName").value.trim(),avatar=$("formalSetupAvatar").value; $("formalSetupError").textContent=""; if(!validPin(pin))return $("formalSetupError").textContent="PINは4〜8桁の数字にしてください。"; if(pin!==confirmPin)return $("formalSetupError").textContent="2つのPINが一致しません。"; if(!name)return $("formalSetupError").textContent="匿名の呼び名を入力してください。"; await setPin(pin); const p=activeProfile(); p.nickname=name.slice(0,16);p.avatar=avatar;saveMeta();closeModal($("formalFirstRun"));renderFormalUi();toast("最初の設定が完了しました。");});
  $("formalPinSubmit").addEventListener("click",submitPin); $("formalPinInput").addEventListener("keydown",e=>{if(e.key==="Enter")submitPin();}); $("formalPinCancel").addEventListener("click",()=>{pendingAdminAction=null;closeModal($("formalPinModal"));});
  $("formalAdultProfileSelect").addEventListener("change",e=>switchProfile(e.target.value)); $("formalAddProfile").addEventListener("click",()=>openEditor()); $("formalProfileEditorCancel").addEventListener("click",()=>closeModal($("formalProfileEditor"))); $("formalProfileEditorSave").addEventListener("click",saveEditor);
  $("formalExportCurrent").addEventListener("click",()=>exportBackup("profile")); $("formalExportAll").addEventListener("click",()=>exportBackup("all")); $("formalImport").addEventListener("click",()=>$("formalImportFile").click()); $("formalImportFile").addEventListener("change",()=>{const file=$("formalImportFile").files?.[0];if(file)prepareImport(file);}); $("formalImportCancel").addEventListener("click",()=>closeModal($("formalImportModal"))); $("formalImportMerge").addEventListener("click",()=>importRecords("merge")); $("formalImportReplace").addEventListener("click",()=>importRecords("replace")); $("formalRollback").addEventListener("click",rollbackImport);
  $("formalChangePin").addEventListener("click",()=>{$("formalNewPin").value="";$("formalNewPinConfirm").value="";$("formalChangePinError").textContent="";openModal($("formalChangePinModal"));}); $("formalChangePinCancel").addEventListener("click",()=>closeModal($("formalChangePinModal"))); $("formalChangePinSave").addEventListener("click",async()=>{const pin=$("formalNewPin").value.trim(),confirmPin=$("formalNewPinConfirm").value.trim();if(!validPin(pin))return $("formalChangePinError").textContent="4〜8桁の数字にしてください。";if(pin!==confirmPin)return $("formalChangePinError").textContent="2つのPINが一致しません。";await setPin(pin);saveMeta();closeModal($("formalChangePinModal"));toast("PINを変更しました。");}); $("formalLockBtn").addEventListener("click",lockAdmin);
  captureAdminGate('.nav-btn[data-page="adult"]',"学習記録と利用者管理を開きます。"); captureAdminGate('#settingsBtn',"現在の利用者の設定を変更します。");
  $("exportBtn")?.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();exportBackup("profile");},true); $("resetBtn")?.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();if(confirm("現在の利用者の学習記録を消しますか？")){suppressAppSave=true;rawRemove(profileDataKey(meta.activeProfileId));location.reload();}},true);
  ["formalPinModal","formalProfileSwitch","formalProfileEditor","formalImportModal","formalChangePinModal"].forEach(id=>$(id).addEventListener("click",e=>{if(e.target===$(id))closeModal($(id));})); document.addEventListener("pointerdown",()=>{if(unlocked)lastAdminActivity=Date.now();},{passive:true}); setInterval(()=>{if(unlocked&&Date.now()-lastAdminActivity>600000)lockAdmin();},30000); document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="hidden"&&unlocked)lockAdmin();});
}
setupEvents(); renderFormalUi(); saveMeta(); if (!meta.adminAuth) openModal($("formalFirstRun")); else if (Object.values(meta.profiles).filter(p=>!p.archived).length>1 && !sessionStorage.getItem("formalProfileChosen")) setTimeout(()=>openModal($("formalProfileSwitch")),200);
